
stages:
    - build
job1:
    # 是否开启 debug 模式
    # variables:
    #     CI_DEBUG_TRACE: "true"
    stage: build
    tags:
        - new testrun
    script:
        - pwd
        - mkdir public
        - cd public
        - echo "test"
    environment:
        name: production
